services:
  nginx:
    image: nginx:1.29.1
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - api
    networks:
      - web
  
  api:
    image: ghcr.io/pisti1555/socialmedia-api:latest
    container_name: socialmedia-api
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      DOTNET_RUNNING_IN_CONTAINER: "true"
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      - app-db
      - identity-db
      - redis-cache
    expose:
      - 8080
    networks:
      - web
    restart: unless-stopped

  app-db:
    image: postgres:17.6
    container_name: postgres-app-db
    volumes:
      - app-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: social_media
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    networks:
      - web
    restart: unless-stopped
    
  identity-db:
    image: postgres:17.6
    container_name: postgres-identity-db
    volumes:
      - identity-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: social_media_identity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    networks:
      - web
    restart: unless-stopped
    
  redis-cache:
    image: redis:8.2.1
    container_name: redis-cache
    expose:
      - 6379
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    driver: bridge

volumes:
  app-db-data:
  identity-db-data:
