name: Bugfix workflow

on:
  push:
    branches:
      - 'bugfix/**'

jobs:
  # Build
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      DOTNET_ENVIRONMENT: Development

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore SocialMediaApi.sln

      - name: Build
        run: dotnet build SocialMediaApi.sln --no-restore -c Release
      
      - name: Run tests
        run: dotnet test -c Release --no-restore --verbosity normal