name: Bugfix workflow

on:
  push:
    branches:
      - 'bugfix/**'

jobs:
  # Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore SocialMediaApi.sln

      - name: Build
        run: dotnet build SocialMediaApi.sln --no-restore -c Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            **/bin/**
            **/obj/**
  
  # Run unit tests
  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Run domain unit tests
        run: dotnet test tests/UnitTests/DomainUnitTests/DomainUnitTests.csproj -c Release --no-build

      - name: Run application unit tests
        run: dotnet test tests/UnitTests/ApplicationUnitTests/ApplicationUnitTests.csproj -c Release --no-build
  
  # Run integration tests
  integration-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Run integration tests
        run: dotnet test tests/IntegrationTests/IntegrationTests.csproj -c Release --no-build